version: '3.8'
services:
  db_pg_15:
    image: postgres:15
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox_user
      POSTGRES_PASSWORD: sandbox_password
    ports:
      - 5432

  spring-boot-app:
    build: .
    ports:
      - 8087:8087
    depends_on:
      - db_pg_15

